test
Signed-off-by: zhangning21 <zhangning21@xiaomi.com>

diff --git a/.github/workflows/parallel_build.yml b/.github/workflows/parallel_build.yml
--- a/.github/workflows/parallel_build.yml
+++ b/.github/workflows/parallel_build.yml
@@ -161,7 +161,8 @@ jobs:
         group: [group1, group2]  # 定义两个组
         include:
           - group: group1
-            tasks: [goldfish-arm64-v8a-ap, goldfish-armeabi-v7a-ap, goldfish-x86_64-ap, stm32h750b-dk:lvgl]  # 第一组任务
+            #tasks: [goldfish-arm64-v8a-ap, goldfish-armeabi-v7a-ap, goldfish-x86_64-ap, stm32h750b-dk:lvgl]  # 第一组任务
+            tasks: [goldfish-x86_64-ap, stm32h750b-dk:lvgl]  # 第一组任务
           - group: group2
             tasks: [goldfish-armeabi-v7a-ap-citest]  # 第二组任务
       fail-fast: false
@@ -355,47 +356,53 @@ jobs:
               ghcr.io/open-vela/openvela-ci-linux_from_apache-nuttx:latest \
               /bin/bash -c "pwd && touch $task && df -h && ls -atl && $build_cmd"
 
-            echo "=== Archiving CI results for $task ==="
+            echo "=== Backup CI results for $task ==="
             ci_artifact_name="${{ matrix.group }}_${task}_${{ needs.setup.outputs.TRIGGER_REPO_NAME }}-${{ github.event.pull_request.number }}"
-            # 使用GitHub CLI上传
-            gh artifact upload "nuttx/nuttx nuttx/vela_*.bin nuttx/.config" --name "$ci_artifact_name" --workflow "$GITHUB_WORKFLOW"
-            mkdir package_back
-            cp nuttx/nuttx nuttx/vela_*.bin nuttx/.config package_back
+            echo $ci_artifact_name
+            mkdir $ci_artifact_name
+            cp nuttx/nuttx nuttx/vela_*.bin nuttx/.config $ci_artifact_name
             
             echo "=== Cleaning up after $task ==="
             sudo ~/bin/repo forall -v -c 'git clean -dfx; git reset --hard HEAD' || true
-
-            if [[ "$task" == *-citest ]]; then
-              echo "Run autotest tasks: $task"
-              STANDARD_CONFIG="${task%-citest*}"
-              docker run --rm \
-                -v ${{ github.workspace }}:/workspace \
-                -w /workspace \
-                ghcr.io/open-vela/openvela-ci-linux_from_apache-nuttx:latest \
-                /bin/bash -c "free -m && df -h && cp package_back/* nuttx/ && ls -atl nuttx && cd tests/scripts/script && pytest -m 'common or ${{ matrix.task }}' ./ -B $STANDARD_CONFIG -L /workspace -P /workspace -F /tmp -R qemu -v --disable-warnings --count=1 --json=/workspace/autotest.json"
-                /bin/bash -c "ls -atl"
-
-              echo "Check autotest result: $task"
-              cd ${{ github.workspace }}
-              mkdir output
-              cp nuttx/nuttx ./*.log ./autotest.json output
-              failed=$(cat autotest.json | jq '.report.summary.failed')
-              if [ "$failed" != "null" ] && [ "$failed" != "0" ]; then
-                echo "autotest failed: $failed"
-                result="failed"
-                exit 1;
-              else
-                echo "autotest passed"
-                result="success"
-              fi
-              echo "::set-output name=AUTOTEST_RESULT::${result}"
-            fi
-
-            echo "=== Archiving autotest results for $task ==="
-            autotest_artifact_name="${{ matrix.group }}_${task}_autotest_${{ needs.setup.outputs.TRIGGER_REPO_NAME }}-${{ github.event.pull_request.number }}"
-            # 使用GitHub CLI上传
-            gh artifact upload "output/" --name "$autotest_artifact_name" --workflow "$GITHUB_WORKFLOW"
           done
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.group }}_${{ matrix.task }}
+          path: |
+            ${{ matrix.group }}_${{ matrix.task }}_${{ needs.setup.outputs.TRIGGER_REPO_NAME }}-${{ github.event.pull_request.number }}
+
+            #   if [[ "$task" == *-citest ]]; then
+            #     echo "Run autotest tasks: $task"
+            #     STANDARD_CONFIG="${task%-citest*}"
+            #     docker run --rm \
+            #       -v ${{ github.workspace }}:/workspace \
+            #       -w /workspace \
+            #       ghcr.io/open-vela/openvela-ci-linux_from_apache-nuttx:latest \
+            #       /bin/bash -c "free -m && df -h && cp package_back/* nuttx/ && ls -atl nuttx && cd tests/scripts/script && pytest -m 'common or ${{ matrix.task }}' ./ -B $STANDARD_CONFIG -L /workspace -P /workspace -F /tmp -R qemu -v --disable-warnings --count=1 --json=/workspace/autotest.json"
+            #       /bin/bash -c "ls -atl"
+
+            #     echo "Check autotest result: $task"
+            #     cd ${{ github.workspace }}
+            #     mkdir output
+            #     cp nuttx/nuttx ./*.log ./autotest.json output
+            #     failed=$(cat autotest.json | jq '.report.summary.failed')
+            #     if [ "$failed" != "null" ] && [ "$failed" != "0" ]; then
+            #       echo "autotest failed: $failed"
+            #       result="failed"
+            #       exit 1;
+            #     else
+            #       echo "autotest passed"
+            #       result="success"
+            #     fi
+            #     echo "::set-output name=AUTOTEST_RESULT::${result}"
+            #   fi
+
+            #   echo "=== Archiving autotest results for $task ==="
+            #   autotest_artifact_name="${{ matrix.group }}_${task}_autotest_${{ needs.setup.outputs.TRIGGER_REPO_NAME }}-${{ github.event.pull_request.number }}"
+            #   # 使用GitHub CLI上传
+            #   gh artifact upload "output/" --name "$autotest_artifact_name" --workflow "$GITHUB_WORKFLOW"
 
 
   # 后置处理作业，用于更新依赖PR状态
