test
Signed-off-by: zhangning21 <zhangning21@xiaomi.com>

diff --git a/.github/workflows/parallel_build.yml b/.github/workflows/parallel_build.yml
--- a/.github/workflows/parallel_build.yml
+++ b/.github/workflows/parallel_build.yml
@@ -258,8 +258,26 @@ jobs:
           name: source
           path: .
 
+      - name: Clean up disk space
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+          sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /etc/mysql /etc/php /opt/hostedtoolcache/CodeQL
+          sudo docker image prune --all --force
+          sudo docker builder prune -a
+          sudo docker system prune -af
+          sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
+          sudo -E apt-get -qq update
+          sudo -E apt-get -qq autoremove --purge
+          sudo -E apt-get -qq clean
+          df -h
+
       - name: Extract sources
-        run: ls -atl .
+        run: ls -atl . && df -h
 
       - name: Docker Login
         uses: docker/login-action@v3
@@ -285,61 +303,55 @@ jobs:
           name: ${{ matrix.task }}_${{ env.REPO_NAME }}-${{ github.event.pull_request.number }}
           path: nuttx/nuttx
 
-      #- name: Clean workspace
-      #  run: |
-      #    echo 'export PATH=~/bin:$PATH' >> $HOME/.bashrc
-      #    curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
-      #    chmod a+x ~/bin/repo
-      #    sudo ~/bin/repo forall -v -c git clean -dfx; git reset --hard HEAD
-      #    cp -r package_back/* nuttx/ || true
-      #    ls -atl package_back/
-
-  # 自动测试作业，依赖于所有CI任务完成
-  autotest:
-    needs: ci-tasks
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code (已在setup作业中完成，此处无需重复)
-        run: echo "Using workspace from setup job"
-
       - name: Run autotest tasks inside Docker container
+        if: endsWith(matrix.task, '-citest')
         run: |
+          echo 'export PATH=~/bin:$PATH' >> $HOME/.bashrc
+          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
+          chmod a+x ~/bin/repo
+          sudo ~/bin/repo forall -v -c git clean -dfx; git reset --hard HEAD
+          cp -r package_back/* nuttx/ || true
+          ls -atl package_back/
+          STANDARD_CONFIG="${matrix.task%-citest*}"
           docker run --rm \
             -v ${{ github.workspace }}:/workspace \
             -w /workspace \
             ghcr.io/open-vela/openvela-ci-linux_from_apache-nuttx:latest \
-            #/bin/bash -c "free -m && df -h && cp package_back/* nuttx/ && ls -atl nuttx && cd tests/scripts/script && pytest -m 'common or goldfish_armeabi_v7a_ap' ./ -B goldfish-armeabi-v7a-ap -L /workspace -P /workspace -F /tmp -R qemu -v --disable-warnings --count=1 --json=/workspace/autotest.json"
+            /bin/bash -c "free -m && df -h && cp package_back/* nuttx/ && ls -atl nuttx && cd tests/scripts/script && pytest -m 'common or ${{ matrix.task }}' ./ -B $STANDARD_CONFIG -L /workspace -P /workspace -F /tmp -R qemu -v --disable-warnings --count=1 --json=/workspace/autotest.json"
             /bin/bash -c "ls -atl"
 
-        #- name: Check autotest result
-        #  id: autotest_result
-        #  run: |
-        #    cd ${{ github.workspace }}
-        #    mkdir output
-        #    cp nuttx/nuttx ./*.log ./autotest.json output
-        #    failed=$(cat autotest.json | jq '.report.summary.failed')
-        #    if [ "$failed" != "null" ] && [ "$failed" != "0" ]; then
-        #      echo "autotest failed: $failed"
-        #      result="failed"
-        #    else
-        #      echo "autotest passed"
-        #      result="success"
-        #    fi
-        #    echo "::set-output name=AUTOTEST_RESULT::${result}"
+      - name: Check autotest result
+        if: endsWith(matrix.task, '-citest')
+        id: autotest_result
+        run: |
+          cd ${{ github.workspace }}
+          mkdir output
+          cp nuttx/nuttx ./*.log ./autotest.json output
+          failed=$(cat autotest.json | jq '.report.summary.failed')
+          if [ "$failed" != "null" ] && [ "$failed" != "0" ]; then
+            echo "autotest failed: $failed"
+            result="failed"
+          else
+            echo "autotest passed"
+            result="success"
+          fi
+          echo "::set-output name=AUTOTEST_RESULT::${result}"
 
-        #- name: Upload Artifact
-        #  uses: actions/upload-artifact@v4
-        #  with:
-        #    name: goldfish-armeabi-v7a-ap-citest_${{ env.REPO_NAME }}-${{ github.event.pull_request.number }}
-        #    path: output/
+      - name: Upload Artifact
+        if: endsWith(matrix.task, '-citest')
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.task }}_autotest_${{ env.REPO_NAME }}-${{ github.event.pull_request.number }}
+          path: output/
 
-        #- name: Exit with autotest exit code
-        #  run: |
-        #    if [ ${{ steps.autotest_result.outputs.AUTOTEST_RESULT }} == "success" ]; then
-        #      exit 0;
-        #    else
-        #      exit 1;
-        #    fi
+      - name: Exit with autotest exit code
+        if: endsWith(matrix.task, '-citest')
+        run: |
+          if [ ${{ steps.autotest_result.outputs.AUTOTEST_RESULT }} == "success" ]; then
+            exit 0;
+          else
+            exit 1;
+          fi
 
   # 后置处理作业，用于更新依赖PR状态
   post-processing:
