Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -89,16 +89,16 @@ jobs:
         for DEPENDENCY in $DEPENDS_ON; do
           REPO_NAME=$(echo $DEPENDENCY | cut -d '#' -f 1)
           PR_NUMBER=$(echo $DEPENDENCY | cut -d '#' -f 2)
-          #PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER")
-          #LATEST_SHA=$(echo "$PR_COMMITS" | jq -r '.head.sha')
-          #if [[ -z "$LATEST_SHA" ]]; then
-          #  echo "No commits found for PR #$PR_NUMBER or invalid API response."
-          #  exit 1
-          #fi
+          PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER")
+          LATEST_SHA=$(echo "$PR_COMMITS" | jq -r '.head.sha')
+          if [[ -z "$LATEST_SHA" ]]; then
+            echo "No commits found for PR #$PR_NUMBER or invalid API response."
+            exit 1
+          fi
           curl -X POST \
             -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/$REPO_NAME/statuses/$PR_NUMBER \
+            https://api.github.com/repos/$REPO_NAME/statuses/$LATEST_SHA \
             -d '{
               "state": "success",
               "description": "CI build passed",
