Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -68,6 +68,15 @@ jobs:
         #    ~/bin/repo sync -c -d --no-tags -j12
         #    df -h
 
+    - name: Get Current Action URL
+      env:
+        GITHUB_REPOSITORY: ${{ github.repository }}
+        GITHUB_RUN_ID: ${{ github.run_id }}
+        GITHUB_SERVER_URL: ${{ github.server_url }}
+      run: |
+        echo "Current Action URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+        echo "CURRENT_ACTION_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
+
     - name: Parse PR Description for Dependencies
       id: parse-dependencies
       run: |
@@ -80,25 +89,21 @@ jobs:
         for DEPENDENCY in $DEPENDS_ON; do
           REPO_NAME=$(echo $DEPENDENCY | cut -d '#' -f 1)
           PR_NUMBER=$(echo $DEPENDENCY | cut -d '#' -f 2)
-          PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER")
-          LATEST_SHA=$(echo "$PR_COMMITS" | jq -r '.head.sha')
-          if [[ -z "$LATEST_SHA" ]]; then
-            echo "No commits found for PR #$PR_NUMBER or invalid API response."
-            exit 1
-          fi
+          #PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER")
+          #LATEST_SHA=$(echo "$PR_COMMITS" | jq -r '.head.sha')
+          $if [[ -z "$LATEST_SHA" ]]; then
+          #  echo "No commits found for PR #$PR_NUMBER or invalid API response."
+          #  exit 1
+          #fi
           curl -X POST \
-            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
-            -H "Accept: application/vnd.github+json" \
-            https://api.github.com/repos/$REPO_NAME/check-runs \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO_NAME/statuses/$PR_NUMBER \
             -d '{
-              "name": "Custom Check",
-              "head_sha": "'$LATEST_SHA'",
-              "status": "completed",
-              "conclusion": "success", # 或者 failure
-              "output": {
-                "title": "PR Check",
-                "summary": "This is a custom check result for PR #'$PR_NUMBER'."
-              }
+              "state": "success",
+              "description": "CI build passed",
+              "context": "continuous-integration/jenkins",
+              "target_url": "${{ env.CURRENT_ACTION_URL }}"
             }'
           # Check if the PR is merged
           #PR_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER" | jq -r .state)
