Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,8 +47,17 @@ jobs:
       run: |
         ~/bin/repo --version
 
-    - name: Add SSH key                                                                                                                                                                                                    
-      run: |                                                                                                                                                                                                               
+    - name: Add SSH key
+      env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+      run: |
+        required_vars=("SSH_PRIVATE_KEY")
+          for var in "${required_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              echo "Error: Required environment variable $var is not set."
+              exit 1
+            fi
+          done
         mkdir -p ~/.ssh                                                                                                                                                                                                    
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa                                                                                                                                                              
         chmod 600 ~/.ssh/id_rsa                                                                                                                                                                                            
